#!/bin/sh
BAT=$(upower -i `upower -e | grep 'BAT'`)
DIS=$(upower -i `upower -e | grep 'BAT'` | grep "state" | awk '{print $2}')

if [ $DIS = "discharging" ] 
then
    ICON=""
else
    ICON=""
fi

upower -i `upower -e | grep 'BAT'` | grep percentage | awk -v icon=$ICON '{printf("%s %.0f%%\n", icon, $2)}'
