#! /bin/sh

sxhkd &

if [[ $(hostname) == 'windows-go-brr' ]]; then
    bspc monitor DVI-D-0 -d I II III IV V 
    bspc monitor DP-2 -d VI VII VIII IX X
elif [[ $(hostname) == 'archboi' ]]; then
    bspc monitor eDP1 -d I II III IV V 
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
