icons_format = "{icon}"

[theme]
theme = "bad-wolf"

[icons]
icons = "material-nf"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon /: $available.eng(w:2) "

[[block]]
block = "battery"
format = " $icon $percentage "
full_format = " $icon $percentage "

[[block]]
block = "external_ip"
format = " $ip "

[[block]]
block = "temperature"
format = " $icon $average "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
warning = 90
info = 75
idle = 55
good = 40

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d-%m-%Y %R:%S') "

