#!/bin/sh

BAT=$(acpi | grep 'remaining\|until charged\|charging' | awk -F ', ' '{ gsub("%","",$2); print $2 }')
DIS=$(acpi | grep 'remaining\|until charged' | awk '{ print $3 }')

if [ "$DIS" = "Discharging," ] 
then
    if [ $BAT -eq 100 ]
    then
        ICON="󰁹"
    elif [ $BAT -ge 90 ]
    then
        ICON="󰂂"
    elif [ $BAT -ge 80 ]
    then
        ICON="󰂁"
    elif [ $BAT -ge 70 ]
    then
        ICON="󰂀"
    elif [ $BAT -ge 60 ]
    then
        ICON="󰁿"
    elif [ $BAT -ge 50 ]
    then
        ICON="󰁾"
    elif [ $BAT -ge 40 ]
    then
        ICON="󰁽"
    elif [ $BAT -ge 30 ]
    then
        ICON="󰁼"
    elif [ $BAT -ge 20 ]
    then
        ICON="󰁻"
    elif [ $BAT -ge 10 ]
    then
        ICON="󰁺"
    else
        ICON="󰂃"
    fi
else
    ICON="󰂄"
fi

printf "%s %s%%\n" "$ICON" "$BAT"
