#!/bin/bash
sleep 1
DISPLAY=":0.0"
HOME=/home/peter/
XAUTHORITY=$HOME/.Xauthority
export DISPLAY XAUTHORITY HOME

setxkbmap prog -variant dk
setxkbmap -option caps:escape
xmodmap -e "keycode 49 = Escape"
xset r rate 400 75
