#!/bin/sh

NUM="${2:-5}"

case "$1" in
    up) pulsemixer --change-volume +"$NUM" ;;
    down) pulsemixer --change-volume -"$NUM" ;;
    mute) pulsemixer --mute ;;
    toggle) pulsemixer --toggle-mute ;;
esac
pkill -RTMIN+10 dwmblocks
